name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"] # Tự động build khi bạn git push
  schedule:
    - cron: '0 */3 * * *' # Tự động húp bài mỗi 3 tiếng (0h, 3h, 6h...)
  workflow_dispatch:      # Kích hoạt nút bấm Build thủ công

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm' # Giúp build nhanh hơn, tiết kiệm tài nguyên
          
      - name: Install dependencies
        run: npm install
        
      - name: Build with Next.js
        run: npm run build
        env:
          VITE_BLOGGER_ID: ${{ secrets.VITE_BLOGGER_ID }} # Lấy ID từ kho mật
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out # Thư mục chứa file tĩnh sau khi build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4